version: '3.8'

services:
  mysql:
    container_name: list-manager-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vibbra-db
    ports:
      - 3312:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
      
  list-manager:
    container_name: list-manager-api
    depends_on: 
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - variables.env
    ports:
      - 8080:8080