CREATE TABLE IF NOT EXISTS user (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
	CONSTRAINT pk_user_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS list (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED,
	title VARCHAR(255) NOT NULL,
	CONSTRAINT pk_list_id PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS item (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
	list_id  BIGINT UNSIGNED NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	CONSTRAINT pk_item_id PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES user(id),
	FOREIGN KEY (list_id) REFERENCES list(id)
);